URL: https://techcrunch.com/
Section:
  - startups/
  - mobile/
  - gadgets/
  - enterprise/
  - social/
  - europe/
  - asia/
Page: page/{num}/
MinPage: 1
MaxPage: 5

Request:
  Timeout: 4
  HeaderFilename: 'src/header.json'

PostsFilename: 'models/posts/{dt}.csv'
SaveBatch: 5

SleepTime: 0.2
MaxLinks: 500
